language: python
matrix:
  include:
    - python: "2.6"
      env: TOX_ENV=py26
    - python: "2.7"
      env: TOX_ENV=py27
    - python: "3.2"
      env: TOX_ENV=py32
    - python: "3.3"
      env: TOX_ENV=py33
    - python: "pypy"
      env: TOX_ENV=pypy
install:
  - pip install tox
  - pip install .
script:
  - tox -e $TOX_ENV
notifications:
  email: false
