language: python
python:
  - "2.6"
  - "3.2"
env:
  - TOX_ENV=py26
  - TOX_ENV=py32
  - TOX_ENV=pypy
install:
  - pip install tox
  - pip install .
script:
  - tox -e $TOX_ENV
notifications:
  - email: false
